# Generated by Django 5.0.4 on 2024-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fines',
            field=models.IntegerField(),
        ),
    ]
