# Generated by Django 5.0.4 on 2024-04-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_user_fines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfp',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='calc.user'),
        ),
    ]
